# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
application_url = "https://your-domain.com"
embedded = true
name = "Section Factory Clone"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes,read_products,read_metaobjects,write_metaobjects,read_files,write_files,read_orders,read_customers"

[auth]
redirect_urls = [ "https://your-domain.com/auth/callback" ]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = [ "app/uninstalled" ]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = [ "app/scopes_update" ]
